[target.libjxr]
type = "lib-no-warns"
include-directories = ["image/sys/", "jxrgluelib/", "common/include/"]
compile-definitions = ["DISABLE_PERF_MEASUREMENT"]
unix.compile-definitions = ["__ANSI__"]
sources = ["**.c"]
